[tool.poetry]
name = "discord-gpt-bot"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{include = "discord_gpt_bot"}]

[tool.poetry.dependencies]
python = "^3.8.6"
discord-py-interactions = "^4"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
